language: node_js
node_js:
  - "stable"
cache: yarn
install:
  - yarn install
script:
  - yarn test -- --coverage

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   on: 
#     branch: gh-pages